# Generated by Django 2.1.5 on 2023-03-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reminder_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
