# Generated by Django 4.1.7 on 2023-04-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_issue_database_damage_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue_database',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
