# Generated by Django 4.1.7 on 2023-04-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_issue_database_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_database',
            name='damage_penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='issue_database',
            name='penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='issue_database',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='issue_database',
            name='tax',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='issue_database',
            name='total_penalty',
            field=models.FloatField(default=0),
        ),
    ]
