# Generated by Django 2.1.5 on 2023-03-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20230323_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_returned',
            field=models.BooleanField(default=True),
        ),
    ]
