# Generated by Django 2.1.5 on 2023-03-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_remove_book_return_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='issue_freq',
            field=models.IntegerField(default=0),
        ),
    ]
