# Generated by Django 4.1.7 on 2023-04-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_return_request_id_alter_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='return_request',
            name='request_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
